version: '3.8'

services:
  redis:
    container_name: go_link_preview_redis
    image: redis:7.0
    command: redis-server --port 8379
    # environment:
    #   - REDISPORT=8379
    ports:
      - "8379:8379"
    restart: unless-stopped
    networks:
      - go_link_preview_network

  app:
    container_name: go_link_preview_app
    image: go_link_preview_generator
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:    
      - GP_PORT=8750
      - USE_CACHE=1
      - REDIS_PORT=8379
      - REDIS_HOST=redis
    ports:
      - "8750:8750"
    restart: unless-stopped
    networks:
      - go_link_preview_network

networks:
  go_link_preview_network:
    driver: bridge